<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CASECommon\Module'                                                      => __DIR__ . '/Module.php',
  'CASECommon\Service\EntityServiceInterface'                              => __DIR__ . '/src/CASECommon/Service/EntityServiceInterface.php',
);
